name: Pull Request
on:
  workflow_dispatch:
    inputs:
      pull_number:
        description: Pull Request number to run benchmark (e.g. 12512)
        required: true
        type: string
      repeats:
        description: number of benchmark repeats
        required: true
        type: string
        default: '10'
jobs:
  benchmark:
    name: Run benchmark
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm run bootstrap

      - name: Run benchmark
        id: run_benchmark
        run: cd runner && pnpm tsx src/cli.ts bench --pull-number="${{ inputs.pull_number }}" --repeats="${{ inputs.repeats }}"
